import { Dosage, Factory, LongTextConverter, ShortTextConverter } from "../../main/ts";
import { DefaultDosageRendererFactory } from "../../main/ts/dosagerenderer/DefaultDosageRendererFactory";
import { DosageRenderer } from "../../main/ts/dosagerenderer/DosageRenderer";
import { OldToNewDosageConverter } from "../../main/ts/helpers/OldToNewDosageConverter";

const longTextExamples: Dosage[] = [
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "endDate": "2019-01-19", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "NightDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "endDate": "2019-01-19", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NoonDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NightDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "TimedDoseWrapper", "time": { "hour": 8, "minute": 0, "second": 0 }, "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "TimedDoseWrapper", "time": { "hour": 12, "minute": 30, "second": 0 }, "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "TimedDoseWrapper", "time": { "hour": 12, "minute": 30, "second": 0 }, "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "TimedDoseWrapper", "time": { "hour": 3, "minute": 1, "second": 0 }, "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "TimedDoseWrapper", "time": { "hour": 21, "minute": 1, "second": 0 }, "doseQuantity": 4, "isAccordingToNeed": false }, { "type": "TimedDoseWrapper", "time": { "hour": 3, "minute": 1, "second": 0 }, "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "TimedDoseWrapper", "time": { "hour": 15, "minute": 1, "second": 0 }, "doseQuantity": 3, "isAccordingToNeed": false }, { "type": "TimedDoseWrapper", "time": { "hour": 9, "minute": 1, "second": 0 }, "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NightDoseWrapper", "doseQuantity": 5, "isAccordingToNeed": false }, { "type": "NoonDoseWrapper", "doseQuantity": 6, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 7, "isAccordingToNeed": false }, { "type": "MorningDoseWrapper", "doseQuantity": 8, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }, { "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }, { "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }, { "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2018-12-04", "endDate": "2018-12-04", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2018-12-04", "endDate": "2018-12-04", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NightDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2020-08-27", "endDate": "2020-09-02", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "tages med rigeligt vand", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NightDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 4, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 0.5, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 4, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1.5, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NoonDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NoonDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "NoonDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 4, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "EveningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "EveningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 0, "allDoses": [{ "type": "EveningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "endDate": "2020-11-01", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-10-27", "endDate": "2020-11-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "endDate": "2020-11-01", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-10-27", "endDate": "2020-11-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 0, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 0, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "startDate": "2020-10-27", "endDate": "2020-11-02", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-10-27", "endDate": "2020-11-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "startDate": "2020-10-27", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-10-27", "endDate": "2020-11-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "startDate": "2020-10-27", "endDate": "2020-11-01", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-10-27", "endDate": "2020-11-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "endDate": "2020-11-30", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-10-27", "endDate": "2020-11-30", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-10-27", "endDate": "2020-11-30", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "endDate": "2021-11-01", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2021-10-25", "endDate": "2021-11-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "startDate": "2021-10-18", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2021-10-25", "endDate": "2021-11-05", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2021-10-25", "endDate": "2021-11-06", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 14, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NoonDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "NoonDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "NoonDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 4, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "EveningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2020-01-22", "endDate": "2020-01-26", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }, { "iterationInterval": 2, "supplText": "", "startDate": "2020-01-27", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2020-01-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }] }] }, { "iterationInterval": 2, "supplText": "", "startDate": "2020-01-23", "endDate": "2020-01-26", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "plaster", "unitPlural": "plastre" }, "structures": [{ "iterationInterval": 3, "supplText": "", "startDate": "2020-06-30", "endDate": "2020-07-29", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }, { "iterationInterval": 4, "supplText": "", "startDate": "2020-07-30", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-10-27", "endDate": "2020-11-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }, { "iterationInterval": 7, "supplText": "", "startDate": "2020-11-02", "endDate": "2020-12-09", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 5, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 4, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2018-12-04", "endDate": "2018-12-10", "days": [] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2019-11-15", "endDate": "2020-05-27", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }, { "iterationInterval": 1, "supplText": "", "startDate": "2020-06-01", "endDate": "2020-07-22", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }, { "iterationInterval": 1, "supplText": "", "startDate": "2020-05-28", "endDate": "2020-05-31", "days": [] }], "isPartOfMultiPeriodDosage": false } },
    { "freeText": { "startDate": "2018-12-04", "text": "1,5 tabl om morgenen" } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 14, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 21, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 21, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 3, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 4, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 4, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 0, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }, { "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 0, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }, { "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2019-04-18", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "TimedDoseWrapper", "time": { "hour": 10, "minute": 0, "second": 0 }, "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "NoonDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "ml", "unitPlural": "ml" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2018-12-04", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "TimedDoseWrapper", "time": { "hour": 8, "minute": 0, "second": 0 }, "doseQuantity": 5, "isAccordingToNeed": false }, { "type": "TimedDoseWrapper", "time": { "hour": 12, "minute": 0, "second": 0 }, "doseQuantity": 10, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2020-01-22", "endDate": "2020-01-26", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2020-01-22", "endDate": "2020-01-26", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }, { "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "endDate": "2020-01-25", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }, { "dayNumber": 6, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-01-22", "endDate": "2021-03-01", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-01-22", "endDate": "2021-01-25", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-01-22", "endDate": "2021-01-22", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-01-22", "endDate": "2021-03-01", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-01-22", "endDate": "2021-03-01", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "startDate": "2020-01-22", "endDate": "2020-04-01", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-01-22", "endDate": "2020-01-24", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }, { "iterationInterval": 7, "supplText": "", "startDate": "2020-01-25", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "endDate": "2020-03-01", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "Bemærkninger til ugeskema", "startDate": "2020-01-22", "endDate": "2020-03-01", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "startDate": "2020-01-22", "endDate": "2020-04-01", "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2020-01-22", "endDate": "2020-01-24", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }, { "iterationInterval": 7, "supplText": "", "startDate": "2020-01-25", "days": [{ "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 6, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unit": "mg" }, "startDate": "2020-01-22", "endDate": "2020-04-01", "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2020-01-22", "endDate": "2020-01-24", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 15, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 15, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "ml", "unitPlural": "ml" }, "structures": [{ "iterationInterval": 0, "startDate": "2019-04-13", "endDate": "2019-04-15", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "NoonDoseWrapper", "doseQuantity": 2.5, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "NoonDoseWrapper", "doseQuantity": 2.5, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
];

const shortTextExamples: Dosage[] = [
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 1, "supplText": "", "startDate": "2019-04-18", "endDate": "2019-04-23", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": true }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2020-08-27", "endDate": "2020-09-02", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 2, "supplText": "", "startDate": "2026-06-03", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "ml", "unitPlural": "ml" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2019-04-13", "endDate": "2019-04-15", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "NoonDoseWrapper", "doseQuantity": 2.5, "isAccordingToNeed": false }] }, { "dayNumber": 3, "allDoses": [{ "type": "NoonDoseWrapper", "doseQuantity": 2.5, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2026-06-03", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "suppl tekst", "startDate": "2026-06-03", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "NightDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "test af suppl", "startDate": "2026-06-03", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "test af suppl", "startDate": "2026-06-03", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 2, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }, { "dayNumber": 4, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-12-01", "endDate": "2021-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-12-01", "endDate": "2021-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 30, "supplText": "", "startDate": "2021-12-01", "endDate": "2022-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 30, "supplText": "", "startDate": "2021-12-01", "endDate": "2021-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 30, "supplText": "", "startDate": "2021-12-01", "endDate": "2022-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 30, "supplText": "", "startDate": "2021-12-01", "endDate": "2021-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 14, "supplText": "", "startDate": "2021-12-01", "endDate": "2022-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 14, "supplText": "", "startDate": "2021-12-01", "endDate": "2021-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 10, "supplText": "", "startDate": "2021-12-01", "endDate": "2022-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 10, "supplText": "", "startDate": "2021-12-01", "endDate": "2021-12-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2026-06-03", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2019-09-01", "endDate": "2019-09-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }, { "iterationInterval": 1, "startDate": "2019-09-02", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2019-09-01", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2016-01-13", "endDate": "2020-06-07", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "EveningDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }, { "iterationInterval": 1, "startDate": "2020-06-08", "endDate": "2022-06-08", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "NightDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2020-06-01", "endDate": "2020-06-07", "days": [] }, { "iterationInterval": 5, "startDate": "2020-06-08", "endDate": "2022-06-08", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "NightDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2016-01-13", "endDate": "2016-01-13", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }, { "iterationInterval": 1, "startDate": "2020-06-08", "endDate": "2022-06-08", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "NightDoseWrapper", "doseQuantity": 2, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2016-01-13", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2016-01-13", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 0.5, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "startDate": "2016-01-13", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "PlainDoseWrapper", "doseQuantity": 0.5, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 7, "supplText": "", "startDate": "2021-10-25", "endDate": "2021-10-25", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2021-10-25", "endDate": "2021-10-25", "days": [] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, "supplText": "", "startDate": "2021-10-25", "endDate": "2021-10-25", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 14, "supplText": "", "startDate": "2021-10-25", "endDate": "2021-10-25", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 1, "isAccordingToNeed": false }, { "type": "EveningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } }
];


const miscExamples: Dosage[] = [
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, supplText: "[Single period longer than dosage days]", "startDate": "2020-08-27", "endDate": "2020-09-02", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [{ "iterationInterval": 0, supplText: "[Single period - no endDate]", "startDate": "2020-08-27", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }], "isPartOfMultiPeriodDosage": false } },
    { "structures": { "unitOrUnits": { "unitSingular": "tablet", "unitPlural": "tabletter" }, "structures": [
        { "iterationInterval": 0, supplText: "[Two periods - first longer than dosage days]", "startDate": "2020-08-27", "endDate": "2020-09-02", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] },
        { "iterationInterval": 0, "startDate": "2020-09-03", "days": [{ "dayNumber": 1, "allDoses": [{ "type": "MorningDoseWrapper", "doseQuantity": 3, "isAccordingToNeed": false }] }] }
    ], "isPartOfMultiPeriodDosage": true } },
]


export function printExamples() {
    const oldLongTextConverter = new LongTextConverter();
    const newLongTextConverter = new DefaultDosageRendererFactory().getDosageRenderer({ html: false, oneLine: false });

    const longTextEx = longTextExamples.slice(0);

    for (let i = 0; i < longTextEx.length; i++) {
        const dosage = longTextEx[i];
        console.log("#" + i);
        compareLongText(dosage, oldLongTextConverter, newLongTextConverter);
    }

    const oldShortTextConverter = new ShortTextConverter();
    const newShortTextConverter = new DefaultDosageRendererFactory().getDosageRenderer({ html: false, oneLine: true });

    const shortTextEx = shortTextExamples.slice(0);

    for (let i = 0; i < shortTextEx.length; i++) {
        const dosage = shortTextEx[i];
        console.log("#" + i);
        compareShortText(dosage, oldShortTextConverter, newShortTextConverter);
    }

    for (let i = 0; i < miscExamples.length; i++) {
        const dosage = miscExamples[i];
        console.log("#" + i);
        compareLongText(dosage, oldLongTextConverter, newLongTextConverter);
    }

}

function compareLongText(dosage: Dosage, oldConverter: LongTextConverter, newConverter: DosageRenderer) {
    const oldTranslation = oldConverter.convert(dosage);
    const newDosage = new OldToNewDosageConverter().convertDosage(dosage);
    const newTranslation = newConverter.render(newDosage);
    console.log("*** " + JSON.stringify(dosage));
    console.log("### " + JSON.stringify(newDosage));
    console.log(`  -> ${Factory.getLongTextConverter().getConverterClassName(dosage)}`);
    console.log("< " + oldTranslation.replace(/\n/g, "\n< "));
    console.log("---");
    console.log("> " + newTranslation.replace(/\n/g, "\n> "));
}

function compareShortText(dosage: Dosage, oldConverter: ShortTextConverter, newConverter: DosageRenderer) {
    const oldTranslation = oldConverter.convert(dosage);
    const newDosage = new OldToNewDosageConverter().convertDosage(dosage);
    const newTranslation = newConverter.render(newDosage);
    console.log("*** " + JSON.stringify(dosage));
    console.log("### " + JSON.stringify(newDosage));
    console.log(`  -> ${Factory.getShortTextConverter().getConverterClassName(dosage)}`);
    if (oldTranslation) {
        console.log("< " + oldTranslation.replace(/\n/g, "\n< "));
    } else {
        console.log("< (none>");
    }
    console.log("---");
    console.log("> " + newTranslation.replace(/\n/g, "\n> "));
}


printExamples();